# Generated by Django 5.2.4 on 2025-07-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_synclog'),
    ]

    operations = [
        migrations.AddField(
            model_name='synclog',
            name='stop_requested',
            field=models.BooleanField(default=False),
        ),
    ]
