# Generated by Django 5.2.4 on 2025-07-18 21:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_syncstatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='synclog',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='synclog',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='synclog',
            name='log',
        ),
        migrations.RemoveField(
            model_name='synclog',
            name='stop_requested',
        ),
        migrations.RemoveField(
            model_name='synclog',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='synclog',
            name='user',
        ),
        migrations.AddField(
            model_name='synclog',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='synclog',
            name='key',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
