# Generated by Django 4.2.11 on 2025-07-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_synclog_options_remove_synclog_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorbill',
            name='raw_data',
            field=models.JSONField(default=dict),
        ),
    ]
